### ISSUE TITLE
Display Map Background

### ISSUE THREAD

**Issue by lmborione** [iTwin/viewer#120]
I tried to had a map provider public key with the following code in the viewer but the map is not displayed:
```JSX
<Viewer
  mapLayerOptions={{
    MapBoxImagery: {
      key: 'mapBoxKey',
      value: process.env.MAPBOX_PUBLIC_KEY // 'pk.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx'
    }
  }}
  iTwinId={iTwinId}
  iModelId={iModelId}
  authClient={authClient}
  enablePerformanceMonitors={true}
/>
```
Thanks.

**Comment by aruniverse** [comment]
The key should be `access_token`

**Comment by lmborione** [comment]
Hi thanks for the reply.
Hi update my viewer with the following :
```JSX
<Viewer
  mapLayerOptions={{
    MapBoxImagery: {
      key: 'access_token',
      value: process.env.MAPBOX_PUBLIC_KEY // 'pk.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx'
    }
  }}
  iTwinId={iTwinId}
  iModelId={iModelId}
  authClient={authClient}
  enablePerformanceMonitors={true}
/>
```
And the map is still not displayed on screen. Furthermore there are no usage on my MapBox account statistics page.

**Comment by aruniverse** [comment]
Sorry @lmborione , we found an issue with our support for MapBox imagery in our core packages. A [fix](https://github.com/iTwin/itwinjs-core/pull/3214) has been made and will be available in iTwin.js 3.0.1
