### ISSUE TITLE
Synchronize tsconfig targets in the monorepo

### ISSUE THREAD

**Issue by kckst8** [iTwin/viewer#133]
multiple different targets are being used. All should be "es2020". Ensure that everything builds and runs after the change

**Comment by aruniverse** [comment]
Take a look at: 
- https://kangax.github.io/compat-table/es2016plus/ & sort by `Engine types`
- [What TypeScript configuration produces output closest to Node.js 16 capabilities?](https://stackoverflow.com/questions/67371787/what-typescript-configuration-produces-output-closest-to-node-js-16-capabilities)
   - I would keep the module as `ES2020`, and would not want to set `"type": "module"` in the package.json yet, I don't want to start importing from `*.js` files yet :/

In the tsconfig for `itwin/viewer-react`, `itwin/web-viewer-react, `itwin/desktop-viewer-react`, they extend the one found in [core](https://github.com/iTwin/itwinjs-core/blob/master/tools/build/tsconfig-base.json), so you will need to manually add an entry for `"target": "ES2020"` to override whats in the base.

Please test the web-viewer-test app in the repo, I think last summer when i tried to update to es2020, webpack4 didnt work with it.
