### ISSUE TITLE
Use iTwinUI error components

### ISSUE THREAD

**Issue by kckst8** [iTwin/viewer#135]
Research if we can replace usage of the itwin-error-handling-react package in the Viewer. Keep in mind that this package is being used in other services so it cannot be deprecated until usage is removed:

https://itwin.github.io/iTwinUI-react/?path=/story/core-errorpage--bad-gateway

**Comment by aruniverse** [comment]
1. Should be able to remove dep on svgr
2. Nuke the svgs and generated components in packages/modules/error-handling-react/src/images/. All the big error svgs should be found in https://www.npmjs.com/package/@itwin/itwinui-illustrations-react, heres the repo for it: https://github.com/iTwin/iTwinUI-icons/tree/main/packages/illustrations/illustrations
3. In packages/modules/error-handling-react/src/containers/Fallback.tsx, use svgs from itwinui-illustrations-react
4. The above will probably need to refactor packages/modules/error-handling-react/src/components/fallback/
