### ISSUE TITLE
Default tools gone with 3.2.0

### ISSUE THREAD

**Issue by lijiayi0921** [iTwin/viewer#208]
Hi,

I recentley upgrated from 3.1 to 3.2, and I just noticed default tools are no longer there with my itwin viewer.

Previously (3.1):
![Capture](https://user-images.githubusercontent.com/10466395/181072895-11de8be0-dccd-4fc2-a66c-f2657d32b571.PNG)

Now (3.2) :
![image](https://user-images.githubusercontent.com/10466395/181073294-b89deb5c-bf71-42f3-b012-b65b2f58d346.png)

Is there something that I missed for the upgrade ?
Thanks
Jiayi

**Comment by aruniverse** [comment]
Please take a look at the breaking changes in our 3.0 release, https://github.com/iTwin/viewer/blob/master/releases/CHANGELOG-3.0.md
