### ISSUE TITLE
Use new progress API in desktop viewer

### ISSUE THREAD

**Issue by aruniverse** [iTwin/viewer#209]
Closing this pr in favor of, https://github.com/iTwin/itwinjs-core/pull/3735
Will look to use the new progress api in the desktop viewer

_Originally posted by @aruniverse in https://github.com/iTwin/itwinjs-core/issues/3069#issuecomment-1198146967_

**Comment by GytisCepk** [comment]
At the moment, progress API for changesets download is not exposed in the frontend and is missing implementation from _imodels-clients_ side. 

This should be revisited after following items are completed:
https://github.com/iTwin/itwinjs-core/issues/4419
https://github.com/iTwin/imodels-clients/pull/136
