### ISSUE TITLE
@itwin/error-handling-react missing dependency

### ISSUE THREAD

**Issue by linasburneika** [iTwin/viewer#214]
@itwin/error-handling-react package depends on @itwin/core-react because it imports sass styles from there. However @itwin/core-react is not in the dependencies of @itwin/error-handling-react. If you happen to use error handling package independently, then sass transpiling fails because of unresolvable imports.

**Comment by aruniverse** [comment]
This pkg has been deprecated and removed completely from the itwin/viewer-react package in our 3.x release.
We will also not be patching any updates to the 2.x pkgs, so you will need to update on your end.
