### ISSUE TITLE
Maximum call stack size exceeded when realityDataAccess is supplied

### ISSUE THREAD

**Issue by dbiguenet** [iTwin/viewer#225]
The viewer doesn't work anymore when realityDataAccess is supplied : 
```javascript
const realityDataAccessClient = useMemo(
    (): RealityDataAccessClient => {
        const realityDataClientOptions: RealityDataClientOptions = {
            baseUrl: "https://" + process.env.IMJS_URL_PREFIX + "api.bentley.com/realitydata",
            authorizationClient: authClient
        };
        return new RealityDataAccessClient(realityDataClientOptions);
    },[authClient],
);
```

```javascript
<Viewer
    authClient={props.authClient}
    blankConnection={{
        name: "Test",
        location: Cartographic.fromDegrees({longitude: -75.686694, latitude: 40.065757, height: 0}),
        extents: new Range3d(-1000, -1000, -100, 1000, 1000, 100),
        iTwinId: process.env.IMJS_PROJECT_ID
    }}
    enablePerformanceMonitors={false}
    realityDataAccess={props.realityDataAccessClient}                        
/>
```

![bug](https://user-images.githubusercontent.com/110406974/205261095-a53ece00-89f6-400f-af3e-73465440cc97.PNG)

Removing
`authorizationClient: authClient`
from reality data access client initialization seems to fix the error.

Environment : 
@itwin/web-viewer-react version: 3.1.1
iTwinJs : 3.4.6

Might be related to #224 ?

**Comment by dbiguenet** [comment]
Update : 
Doesn't work since 3.0.9

**Comment by aruniverse** [comment]
Guess this line broke it, https://github.com/iTwin/viewer/pull/218/files#diff-8d5aa7547013bfbb02cb24d8c6699445fc2e85755643b78510d8c47db1e83ee0R163

This is definitely related to #224 as well, with this change https://github.com/iTwin/viewer/pull/218/files#diff-8d5aa7547013bfbb02cb24d8c6699445fc2e85755643b78510d8c47db1e83ee0R158
