### ISSUE TITLE
Switching to Frontstage with Blank iModelConnection does not cause the active iModel Connection to be blank

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/viewer#226]
When a Frontstage is declared, the viewState and iModelConnection can be passed as arguments. Passing a blank view state and a blank iModelConnection causes the view to appear blank. I would have expected the active iModelConnection to be reported as blank as well. However, UiFramework.getIModelConnection() still reports the iModelConnection as not being blank.

A sandbox demonstrating this behavior can be found here: https://www.itwinjs.org/sandboxes/AlfonsoMartello/Blank-iModel-Connection-Frontstage-Issue. 

Note: The sandbox is currently using Viewer@2.x, but I was able to reproduce this behvaiour in an iTwin Viewer application using Viewer@3.x.

**Comment by ben-polinsky** [comment]
Looks like an AppUI issue, but since it's 2 years old I'll close. If the issue persists and it's on the viewer's end, reopen and we'll take a look.
