### ISSUE TITLE
cra templates open ssl error with react-scripts@4

### ISSUE THREAD

**Issue by yashincontrol** [iTwin/viewer#230]
Created an iModel according to https://developer.bentley.com/tutorials/web-application-quick-start/ and was getting the following error: "error:0308010C:digital envelope routines::unsupported". Upon changing` "start": "react-scripts --max_old_space_size=4096 start"` to `"start": "react-scripts --max_old_space_size=4096  --openssl-legacy-provider start"` in package.json I was able to npm start and view the iModel.

**Comment by ben-polinsky** [comment]
@aruniverse know anyone who came across this? @yashincontrol was using node 18.x...

**Comment by aruniverse** [comment]
Gah. This is probably an OpenSSL issue. Node 18 moved to OpenSSL 3, [see](https://nodejs.org/en/blog/announcements/nodejs16-eol/). 

Thanks for reporting this; need to see what can be done at the react-scripts level, if anything

**Comment by aruniverse** [comment]
This appears to only be an issue with react-scripts@4, and its been fixed in @5. Will update the templates to use v5
