### ISSUE TITLE
Enhancement to configure a redux middleware

### ISSUE THREAD

**Issue by supriyabhosle** [iTwin/viewer#242]
Currently we have some table components that we would like to use as a UI Widget provider. But these components are using redux thunk. Can a support to configure a redux middleware also be provided?

**Comment by aruniverse** [comment]
Have you looked at https://www.itwinjs.org/learning/ui/appui-react/state/?

What you want might be already possible using the StateManager and ReducerRegistry from AppUi

**Comment by aruniverse** [comment]
possibily look into something like https://twitter.com/_georgemoller/status/1703935267327901722 to inject providers into the viewer; eg IModelJsViewProvider from bentley/imdoeljs-react hooks
