### ISSUE TITLE
Integrate `@itwin/unified-selection` into viewer

### ISSUE THREAD

**Issue by saskliutas** [iTwin/viewer#317]
Integrate `@itwin/unified-selection` for unified selection handling. If `selectionStorage` is passed to `Viewer` component it should use [`enableUnifiedSelectionSyncWithIModel`](https://github.com/iTwin/presentation/tree/master/packages/unified-selection#imodel-selection-synchronization-with-unified-selection) to synchronize hilited element with unified selection instead of [viewWithUnifiedSelection](https://github.com/iTwin/viewer/blob/0359ac61df1dab0c330b337ca77f1a6e87ac4fd3/packages/modules/viewer-react/src/components/app-ui/providers/UnifiedSelectionViewportControl.tsx#L17) HOC

**Comment by aruniverse** [comment]
Will this be a direct dep or a new peer?
