### ISSUE TITLE
PropertyEditorManager.registerEditor error: type 'navigation' already registered to 'NavigationPropertyEditor'

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/viewer#324]
Bunch of errors when starting the web-viewer-test relating to double registration of Property Editors from Presentation to AppUI. This probably only occurs in development, or when using mismatched versions of presentation-components.

**Comment by aruniverse** [comment]
Likely a bug from https://github.com/iTwin/viewer/pull/323
Need to synchronize all versions of presentation-components across the repo

**Comment by ben-polinsky** [comment]
Yep, sorry meant to link to it. Fix incoming
