### ISSUE TITLE
[desktop-viewer] stuck loading while fetching imodels 

### ISSUE THREAD

**Issue by edemiaochu** [iTwin/viewer#336]
in desktop-viewer-react project, when i use `npm start`, the imodels page keeps loading.  when i use `serve -s ./build `,the imodels page can load normally. why?

![Image](https://github.com/user-attachments/assets/68237e94-b6b2-4a59-8927-b7e1c706f9b3)

**Comment by edemiaochu** [comment]
sorry ,in desktop-viewer-test project.

**Comment by aruniverse** [comment]
Hi! Have you inspected the network tab? Are the requests to `api.bentley.com/imodels` resolving?

**Comment by edemiaochu** [comment]
Hi，And, when i run  `npm start` to start, the file opened is snapshotconnection,can't edit,but,when i use `serve -s ./build `and `npm run electron:debug` to start, the opened file is briefcaseconnection, do you konw why?

**Comment by edemiaochu** [comment]
> Hi! Have you inspected the network tab? Are the requests to `api.bentley.com/imodels` resolving?
yes，![Image](https://github.com/user-attachments/assets/4fd71576-087c-49b1-b1a5-267116d6e837)

**Comment by edemiaochu** [comment]
> Hi! Have you inspected the network tab? Are the requests to `api.bentley.com/imodels` resolving?

H i，yes ，the   status is 200

**Comment by MichaelSwigerAtBentley** [comment]
Hi, to clarify, does the iModels page keep loading when attempting to access a specific iTwin's iModels via the 'downloads' option?

**Comment by edemiaochu** [comment]
> Hi, to clarify, does the iModels page keep loading when attempting to access a specific iTwin's iModels via the 'downloads' option?

Hi ,  no, imodels keep loading.  I can't see `download` option.[when i run 'npm start']

**Comment by MichaelSwigerAtBentley** [comment]
Hi, I'm having trouble recreating this. 

When running npm start from the `viewer\packages\apps\desktop-viewer-test` App.tsx is called, which should load the Home.tsx file.

Could you post your console out? Its possible something is occurring during App.tsx initialization

**Comment by edemiaochu** [comment]
Hi, Do you mean these ? One is backend console out ,the other is frontend console out

**Comment by MichaelSwigerAtBentley** [comment]
Yes, those were the consoles I was referring to, thanks

**Comment by MichaelSwigerAtBentley** [comment]
I believe I have recreated the issue.

A function seems to be aborting the imodels api calls before they can fully resolve.

It seems possible that when you use `npm start` to start, the app is making a request for an iTwin via an api call and that request is timing out. The preflight handshake might be returning 200, which is what you are seeing, but the actual response never arrives. When you use serve you are loading a local .bim file, which is working as normal, thus the discrepancy. 

Could you take a screenshot of your network tab while searching for `api.bentley.com/imodels` requests?

**Comment by MichaelSwigerAtBentley** [comment]
A potential solution:

At lines 31 and 33 in `\viewer\packages\apps\desktop-viewer-test\src\frontend\index.tsx`, there is a React.StrictMode wrapper. 

Try removing that wrapper, then rebuild and attempt the api call again.
