### ISSUE TITLE
no way to create a sign in frontstage without first loading a snapshot model

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/viewer#34]
looking at [this line of `BaseViewer`](https://github.com/iTwin/viewer/blob/e35a829a3189f71eb18579d5d22f33e3b3cbe2ef/packages/modules/viewer-react/src/components/BaseViewer.tsx#L110), the viewer won't load unless `IModelApp`'s authorizationClient is authorized, which won't
happen until either:
- a user signs in
or
- snapshotPath is set: https://github.com/iTwin/viewer/blob/e35a829a3189f71eb18579d5d22f33e3b3cbe2ef/packages/modules/viewer-react/src/components/BaseViewer.tsx#L52

I am trying to migrate an application from the older `@bentley/itwin-viewer-react`, but I was using a custom default frontstage to handle authenticating users, which is no longer possible. Is it possible to re-enable the previous behavior?

**Comment by MichaelBelousov** [comment]
another issue is that some components I want to use in my sign in page (i.e. `SignIn` from `@bentley/ui-framework`) require the UiFramework to be initialized, but the viewer is responsible for that, so am I supposed to render the viewer component but make it hidden with the sign in page over it, and it will successfully load once the viewer initializes the UiFramework?

**Comment by MichaelBelousov** [comment]
as a work around, I may ship a snapshot with our app to load silently at initialization time.

**Comment by MichaelBelousov** [comment]
also, we are planning on open sourcing the application I'm working on soon, and it would be unfortunate if I had to publish it with a hack, since it's not intended to open a snapshot model on startup, but we will be documenting how we do it anyway without showing the user just to get our sign in screen working.

**Comment by aruniverse** [comment]
iirc, this was resolved, right @MichaelBelousov ? If so, could you close the issue.

**Comment by aruniverse** [comment]
closing this issue, pretty sure it was resolved; can re-open if not
